/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarRoomRouteImport } from './routes/_authenticated/war-room'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedStrategyLabRouteImport } from './routes/_authenticated/strategy-lab'
import { Route as AuthenticatedStrategicMemoryRouteImport } from './routes/_authenticated/strategic-memory'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeasonsRouteImport } from './routes/_authenticated/seasons'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRegimesRouteImport } from './routes/_authenticated/regimes'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedRealRiskRouteImport } from './routes/_authenticated/real-risk'
import { Route as AuthenticatedRealDashboardRouteImport } from './routes/_authenticated/real-dashboard'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedPostTradeRouteImport } from './routes/_authenticated/post-trade'
import { Route as AuthenticatedPipelineDiagnosticsRouteImport } from './routes/_authenticated/pipeline-diagnostics'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedMetricsRouteImport } from './routes/_authenticated/metrics'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedKillSwitchRouteImport } from './routes/_authenticated/kill-switch'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCouncilRouteImport } from './routes/_authenticated/council'
import { Route as AuthenticatedCommitteeRouteImport } from './routes/_authenticated/committee'
import { Route as AuthenticatedBinanceWalletHealthRouteImport } from './routes/_authenticated/binance-wallet-health'
import { Route as AuthenticatedBinanceFeeAuditRouteImport } from './routes/_authenticated/binance-fee-audit'
import { Route as AuthenticatedBinanceBrainRouteImport } from './routes/_authenticated/binance-brain'
import { Route as AuthenticatedBinanceAuditRouteImport } from './routes/_authenticated/binance-audit'
import { Route as AuthenticatedB3WdoRouteImport } from './routes/_authenticated/b3-wdo'
import { Route as AuthenticatedB3SimHistoryRouteImport } from './routes/_authenticated/b3-sim-history'
import { Route as AuthenticatedB3Mt5simRouteImport } from './routes/_authenticated/b3-mt5sim'
import { Route as AuthenticatedB3AuditoriaRouteImport } from './routes/_authenticated/b3-auditoria'
import { Route as AuthenticatedB3RouteImport } from './routes/_authenticated/b3'
import { Route as AuthenticatedAutoDashboardRouteImport } from './routes/_authenticated/auto-dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedApprovalDeskRouteImport } from './routes/_authenticated/approval-desk'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentRankingsRouteImport } from './routes/_authenticated/agent-rankings'
import { Route as AuthenticatedBacktestIndexRouteImport } from './routes/_authenticated/backtest.index'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedLibraryExpertIdRouteImport } from './routes/_authenticated/library.$expertId'
import { Route as AuthenticatedBacktestNewRouteImport } from './routes/_authenticated/backtest.new'
import { Route as AuthenticatedBacktestDataRouteImport } from './routes/_authenticated/backtest.data'
import { Route as AuthenticatedBacktestCriteriaRouteImport } from './routes/_authenticated/backtest.criteria'
import { Route as AuthenticatedBacktestRunIdRouteImport } from './routes/_authenticated/backtest.$runId'
import { Route as AuthenticatedAuditReportIdRouteImport } from './routes/_authenticated/audit.$reportId'
import { Route as AuthenticatedAnalysisAssetIdRouteImport } from './routes/_authenticated/analysis.$assetId'
import { Route as ApiPublicHooksWeeklyReportRouteImport } from './routes/api/public/hooks/weekly-report'
import { Route as ApiPublicHooksPipelineTickRouteImport } from './routes/api/public/hooks/pipeline-tick'
import { Route as ApiPublicHooksHealthRouteImport } from './routes/api/public/hooks/health'
import { Route as ApiPublicHooksDailyReportRouteImport } from './routes/api/public/hooks/daily-report'
import { Route as ApiPublicHooksConfidenceRecomputeRouteImport } from './routes/api/public/hooks/confidence-recompute'
import { Route as ApiPublicHooksB3SimulationTickRouteImport } from './routes/api/public/hooks/b3-simulation-tick'
import { Route as ApiPublicHooksB3Mt5simTickIngestRouteImport } from './routes/api/public/hooks/b3-mt5sim-tick-ingest'
import { Route as ApiPublicHooksB3Mt5simTickRouteImport } from './routes/api/public/hooks/b3-mt5sim-tick'
import { Route as ApiPublicHooksB3Mt5CommandsPendingRouteImport } from './routes/api/public/hooks/b3-mt5-commands-pending'
import { Route as ApiPublicHooksB3Mt5CommandsAckRouteImport } from './routes/api/public/hooks/b3-mt5-commands-ack'
import { Route as ApiPublicHooksAutoTickRouteImport } from './routes/api/public/hooks/auto-tick'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarRoomRoute = AuthenticatedWarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategyLabRoute =
  AuthenticatedStrategyLabRouteImport.update({
    id: '/strategy-lab',
    path: '/strategy-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategicMemoryRoute =
  AuthenticatedStrategicMemoryRouteImport.update({
    id: '/strategic-memory',
    path: '/strategic-memory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonsRoute = AuthenticatedSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegimesRoute = AuthenticatedRegimesRouteImport.update({
  id: '/regimes',
  path: '/regimes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRealRiskRoute = AuthenticatedRealRiskRouteImport.update({
  id: '/real-risk',
  path: '/real-risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealDashboardRoute =
  AuthenticatedRealDashboardRouteImport.update({
    id: '/real-dashboard',
    path: '/real-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostTradeRoute = AuthenticatedPostTradeRouteImport.update({
  id: '/post-trade',
  path: '/post-trade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineDiagnosticsRoute =
  AuthenticatedPipelineDiagnosticsRouteImport.update({
    id: '/pipeline-diagnostics',
    path: '/pipeline-diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetricsRoute = AuthenticatedMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKillSwitchRoute = AuthenticatedKillSwitchRouteImport.update({
  id: '/kill-switch',
  path: '/kill-switch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouncilRoute = AuthenticatedCouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeRoute = AuthenticatedCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBinanceWalletHealthRoute =
  AuthenticatedBinanceWalletHealthRouteImport.update({
    id: '/binance-wallet-health',
    path: '/binance-wallet-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBinanceFeeAuditRoute =
  AuthenticatedBinanceFeeAuditRouteImport.update({
    id: '/binance-fee-audit',
    path: '/binance-fee-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBinanceBrainRoute =
  AuthenticatedBinanceBrainRouteImport.update({
    id: '/binance-brain',
    path: '/binance-brain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBinanceAuditRoute =
  AuthenticatedBinanceAuditRouteImport.update({
    id: '/binance-audit',
    path: '/binance-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedB3WdoRoute = AuthenticatedB3WdoRouteImport.update({
  id: '/b3-wdo',
  path: '/b3-wdo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedB3SimHistoryRoute =
  AuthenticatedB3SimHistoryRouteImport.update({
    id: '/b3-sim-history',
    path: '/b3-sim-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedB3Mt5simRoute = AuthenticatedB3Mt5simRouteImport.update({
  id: '/b3-mt5sim',
  path: '/b3-mt5sim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedB3AuditoriaRoute =
  AuthenticatedB3AuditoriaRouteImport.update({
    id: '/b3-auditoria',
    path: '/b3-auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedB3Route = AuthenticatedB3RouteImport.update({
  id: '/b3',
  path: '/b3',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoDashboardRoute =
  AuthenticatedAutoDashboardRouteImport.update({
    id: '/auto-dashboard',
    path: '/auto-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalDeskRoute =
  AuthenticatedApprovalDeskRouteImport.update({
    id: '/approval-desk',
    path: '/approval-desk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRankingsRoute =
  AuthenticatedAgentRankingsRouteImport.update({
    id: '/agent-rankings',
    path: '/agent-rankings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacktestIndexRoute =
  AuthenticatedBacktestIndexRouteImport.update({
    id: '/backtest/',
    path: '/backtest/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedLibraryExpertIdRoute =
  AuthenticatedLibraryExpertIdRouteImport.update({
    id: '/$expertId',
    path: '/$expertId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedBacktestNewRoute =
  AuthenticatedBacktestNewRouteImport.update({
    id: '/backtest/new',
    path: '/backtest/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacktestDataRoute =
  AuthenticatedBacktestDataRouteImport.update({
    id: '/backtest/data',
    path: '/backtest/data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacktestCriteriaRoute =
  AuthenticatedBacktestCriteriaRouteImport.update({
    id: '/backtest/criteria',
    path: '/backtest/criteria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacktestRunIdRoute =
  AuthenticatedBacktestRunIdRouteImport.update({
    id: '/backtest/$runId',
    path: '/backtest/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditReportIdRoute =
  AuthenticatedAuditReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedAuditRoute,
  } as any)
const AuthenticatedAnalysisAssetIdRoute =
  AuthenticatedAnalysisAssetIdRouteImport.update({
    id: '/analysis/$assetId',
    path: '/analysis/$assetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksWeeklyReportRoute =
  ApiPublicHooksWeeklyReportRouteImport.update({
    id: '/api/public/hooks/weekly-report',
    path: '/api/public/hooks/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPipelineTickRoute =
  ApiPublicHooksPipelineTickRouteImport.update({
    id: '/api/public/hooks/pipeline-tick',
    path: '/api/public/hooks/pipeline-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthRoute = ApiPublicHooksHealthRouteImport.update({
  id: '/api/public/hooks/health',
  path: '/api/public/hooks/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyReportRoute =
  ApiPublicHooksDailyReportRouteImport.update({
    id: '/api/public/hooks/daily-report',
    path: '/api/public/hooks/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksConfidenceRecomputeRoute =
  ApiPublicHooksConfidenceRecomputeRouteImport.update({
    id: '/api/public/hooks/confidence-recompute',
    path: '/api/public/hooks/confidence-recompute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksB3SimulationTickRoute =
  ApiPublicHooksB3SimulationTickRouteImport.update({
    id: '/api/public/hooks/b3-simulation-tick',
    path: '/api/public/hooks/b3-simulation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksB3Mt5simTickIngestRoute =
  ApiPublicHooksB3Mt5simTickIngestRouteImport.update({
    id: '/api/public/hooks/b3-mt5sim-tick-ingest',
    path: '/api/public/hooks/b3-mt5sim-tick-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksB3Mt5simTickRoute =
  ApiPublicHooksB3Mt5simTickRouteImport.update({
    id: '/api/public/hooks/b3-mt5sim-tick',
    path: '/api/public/hooks/b3-mt5sim-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksB3Mt5CommandsPendingRoute =
  ApiPublicHooksB3Mt5CommandsPendingRouteImport.update({
    id: '/api/public/hooks/b3-mt5-commands-pending',
    path: '/api/public/hooks/b3-mt5-commands-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksB3Mt5CommandsAckRoute =
  ApiPublicHooksB3Mt5CommandsAckRouteImport.update({
    id: '/api/public/hooks/b3-mt5-commands-ack',
    path: '/api/public/hooks/b3-mt5-commands-ack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoTickRoute = ApiPublicHooksAutoTickRouteImport.update({
  id: '/api/public/hooks/auto-tick',
  path: '/api/public/hooks/auto-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent-rankings': typeof AuthenticatedAgentRankingsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/approval-desk': typeof AuthenticatedApprovalDeskRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/auto-dashboard': typeof AuthenticatedAutoDashboardRoute
  '/b3': typeof AuthenticatedB3Route
  '/b3-auditoria': typeof AuthenticatedB3AuditoriaRoute
  '/b3-mt5sim': typeof AuthenticatedB3Mt5simRoute
  '/b3-sim-history': typeof AuthenticatedB3SimHistoryRoute
  '/b3-wdo': typeof AuthenticatedB3WdoRoute
  '/binance-audit': typeof AuthenticatedBinanceAuditRoute
  '/binance-brain': typeof AuthenticatedBinanceBrainRoute
  '/binance-fee-audit': typeof AuthenticatedBinanceFeeAuditRoute
  '/binance-wallet-health': typeof AuthenticatedBinanceWalletHealthRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/council': typeof AuthenticatedCouncilRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/kill-switch': typeof AuthenticatedKillSwitchRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/metrics': typeof AuthenticatedMetricsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pipeline-diagnostics': typeof AuthenticatedPipelineDiagnosticsRoute
  '/post-trade': typeof AuthenticatedPostTradeRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/real-dashboard': typeof AuthenticatedRealDashboardRoute
  '/real-risk': typeof AuthenticatedRealRiskRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/regimes': typeof AuthenticatedRegimesRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/risk': typeof AuthenticatedRiskRoute
  '/seasons': typeof AuthenticatedSeasonsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategic-memory': typeof AuthenticatedStrategicMemoryRoute
  '/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/war-room': typeof AuthenticatedWarRoomRoute
  '/analysis/$assetId': typeof AuthenticatedAnalysisAssetIdRoute
  '/audit/$reportId': typeof AuthenticatedAuditReportIdRoute
  '/backtest/$runId': typeof AuthenticatedBacktestRunIdRoute
  '/backtest/criteria': typeof AuthenticatedBacktestCriteriaRoute
  '/backtest/data': typeof AuthenticatedBacktestDataRoute
  '/backtest/new': typeof AuthenticatedBacktestNewRoute
  '/library/$expertId': typeof AuthenticatedLibraryExpertIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/backtest/': typeof AuthenticatedBacktestIndexRoute
  '/api/public/hooks/auto-tick': typeof ApiPublicHooksAutoTickRoute
  '/api/public/hooks/b3-mt5-commands-ack': typeof ApiPublicHooksB3Mt5CommandsAckRoute
  '/api/public/hooks/b3-mt5-commands-pending': typeof ApiPublicHooksB3Mt5CommandsPendingRoute
  '/api/public/hooks/b3-mt5sim-tick': typeof ApiPublicHooksB3Mt5simTickRoute
  '/api/public/hooks/b3-mt5sim-tick-ingest': typeof ApiPublicHooksB3Mt5simTickIngestRoute
  '/api/public/hooks/b3-simulation-tick': typeof ApiPublicHooksB3SimulationTickRoute
  '/api/public/hooks/confidence-recompute': typeof ApiPublicHooksConfidenceRecomputeRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/hooks/pipeline-tick': typeof ApiPublicHooksPipelineTickRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent-rankings': typeof AuthenticatedAgentRankingsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/approval-desk': typeof AuthenticatedApprovalDeskRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/auto-dashboard': typeof AuthenticatedAutoDashboardRoute
  '/b3': typeof AuthenticatedB3Route
  '/b3-auditoria': typeof AuthenticatedB3AuditoriaRoute
  '/b3-mt5sim': typeof AuthenticatedB3Mt5simRoute
  '/b3-sim-history': typeof AuthenticatedB3SimHistoryRoute
  '/b3-wdo': typeof AuthenticatedB3WdoRoute
  '/binance-audit': typeof AuthenticatedBinanceAuditRoute
  '/binance-brain': typeof AuthenticatedBinanceBrainRoute
  '/binance-fee-audit': typeof AuthenticatedBinanceFeeAuditRoute
  '/binance-wallet-health': typeof AuthenticatedBinanceWalletHealthRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/council': typeof AuthenticatedCouncilRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/kill-switch': typeof AuthenticatedKillSwitchRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/metrics': typeof AuthenticatedMetricsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pipeline-diagnostics': typeof AuthenticatedPipelineDiagnosticsRoute
  '/post-trade': typeof AuthenticatedPostTradeRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/real-dashboard': typeof AuthenticatedRealDashboardRoute
  '/real-risk': typeof AuthenticatedRealRiskRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/regimes': typeof AuthenticatedRegimesRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/risk': typeof AuthenticatedRiskRoute
  '/seasons': typeof AuthenticatedSeasonsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategic-memory': typeof AuthenticatedStrategicMemoryRoute
  '/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/war-room': typeof AuthenticatedWarRoomRoute
  '/analysis/$assetId': typeof AuthenticatedAnalysisAssetIdRoute
  '/audit/$reportId': typeof AuthenticatedAuditReportIdRoute
  '/backtest/$runId': typeof AuthenticatedBacktestRunIdRoute
  '/backtest/criteria': typeof AuthenticatedBacktestCriteriaRoute
  '/backtest/data': typeof AuthenticatedBacktestDataRoute
  '/backtest/new': typeof AuthenticatedBacktestNewRoute
  '/library/$expertId': typeof AuthenticatedLibraryExpertIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/backtest': typeof AuthenticatedBacktestIndexRoute
  '/api/public/hooks/auto-tick': typeof ApiPublicHooksAutoTickRoute
  '/api/public/hooks/b3-mt5-commands-ack': typeof ApiPublicHooksB3Mt5CommandsAckRoute
  '/api/public/hooks/b3-mt5-commands-pending': typeof ApiPublicHooksB3Mt5CommandsPendingRoute
  '/api/public/hooks/b3-mt5sim-tick': typeof ApiPublicHooksB3Mt5simTickRoute
  '/api/public/hooks/b3-mt5sim-tick-ingest': typeof ApiPublicHooksB3Mt5simTickIngestRoute
  '/api/public/hooks/b3-simulation-tick': typeof ApiPublicHooksB3SimulationTickRoute
  '/api/public/hooks/confidence-recompute': typeof ApiPublicHooksConfidenceRecomputeRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/hooks/pipeline-tick': typeof ApiPublicHooksPipelineTickRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agent-rankings': typeof AuthenticatedAgentRankingsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/approval-desk': typeof AuthenticatedApprovalDeskRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRouteWithChildren
  '/_authenticated/auto-dashboard': typeof AuthenticatedAutoDashboardRoute
  '/_authenticated/b3': typeof AuthenticatedB3Route
  '/_authenticated/b3-auditoria': typeof AuthenticatedB3AuditoriaRoute
  '/_authenticated/b3-mt5sim': typeof AuthenticatedB3Mt5simRoute
  '/_authenticated/b3-sim-history': typeof AuthenticatedB3SimHistoryRoute
  '/_authenticated/b3-wdo': typeof AuthenticatedB3WdoRoute
  '/_authenticated/binance-audit': typeof AuthenticatedBinanceAuditRoute
  '/_authenticated/binance-brain': typeof AuthenticatedBinanceBrainRoute
  '/_authenticated/binance-fee-audit': typeof AuthenticatedBinanceFeeAuditRoute
  '/_authenticated/binance-wallet-health': typeof AuthenticatedBinanceWalletHealthRoute
  '/_authenticated/committee': typeof AuthenticatedCommitteeRoute
  '/_authenticated/council': typeof AuthenticatedCouncilRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/kill-switch': typeof AuthenticatedKillSwitchRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/metrics': typeof AuthenticatedMetricsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pipeline-diagnostics': typeof AuthenticatedPipelineDiagnosticsRoute
  '/_authenticated/post-trade': typeof AuthenticatedPostTradeRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/real-dashboard': typeof AuthenticatedRealDashboardRoute
  '/_authenticated/real-risk': typeof AuthenticatedRealRiskRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/regimes': typeof AuthenticatedRegimesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/seasons': typeof AuthenticatedSeasonsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategic-memory': typeof AuthenticatedStrategicMemoryRoute
  '/_authenticated/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/war-room': typeof AuthenticatedWarRoomRoute
  '/_authenticated/analysis/$assetId': typeof AuthenticatedAnalysisAssetIdRoute
  '/_authenticated/audit/$reportId': typeof AuthenticatedAuditReportIdRoute
  '/_authenticated/backtest/$runId': typeof AuthenticatedBacktestRunIdRoute
  '/_authenticated/backtest/criteria': typeof AuthenticatedBacktestCriteriaRoute
  '/_authenticated/backtest/data': typeof AuthenticatedBacktestDataRoute
  '/_authenticated/backtest/new': typeof AuthenticatedBacktestNewRoute
  '/_authenticated/library/$expertId': typeof AuthenticatedLibraryExpertIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/backtest/': typeof AuthenticatedBacktestIndexRoute
  '/api/public/hooks/auto-tick': typeof ApiPublicHooksAutoTickRoute
  '/api/public/hooks/b3-mt5-commands-ack': typeof ApiPublicHooksB3Mt5CommandsAckRoute
  '/api/public/hooks/b3-mt5-commands-pending': typeof ApiPublicHooksB3Mt5CommandsPendingRoute
  '/api/public/hooks/b3-mt5sim-tick': typeof ApiPublicHooksB3Mt5simTickRoute
  '/api/public/hooks/b3-mt5sim-tick-ingest': typeof ApiPublicHooksB3Mt5simTickIngestRoute
  '/api/public/hooks/b3-simulation-tick': typeof ApiPublicHooksB3SimulationTickRoute
  '/api/public/hooks/confidence-recompute': typeof ApiPublicHooksConfidenceRecomputeRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/hooks/pipeline-tick': typeof ApiPublicHooksPipelineTickRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent-rankings'
    | '/agents'
    | '/alerts'
    | '/approval-desk'
    | '/assets'
    | '/audit'
    | '/auto-dashboard'
    | '/b3'
    | '/b3-auditoria'
    | '/b3-mt5sim'
    | '/b3-sim-history'
    | '/b3-wdo'
    | '/binance-audit'
    | '/binance-brain'
    | '/binance-fee-audit'
    | '/binance-wallet-health'
    | '/committee'
    | '/council'
    | '/dashboard'
    | '/governance'
    | '/incidents'
    | '/intelligence'
    | '/kill-switch'
    | '/knowledge'
    | '/library'
    | '/logs'
    | '/metrics'
    | '/operations'
    | '/orders'
    | '/pipeline-diagnostics'
    | '/post-trade'
    | '/radar'
    | '/ranking'
    | '/real-dashboard'
    | '/real-risk'
    | '/recommendations'
    | '/regimes'
    | '/reports'
    | '/risk'
    | '/seasons'
    | '/settings'
    | '/strategic-memory'
    | '/strategy-lab'
    | '/supervisor'
    | '/wallet'
    | '/war-room'
    | '/analysis/$assetId'
    | '/audit/$reportId'
    | '/backtest/$runId'
    | '/backtest/criteria'
    | '/backtest/data'
    | '/backtest/new'
    | '/library/$expertId'
    | '/reports/$reportId'
    | '/backtest/'
    | '/api/public/hooks/auto-tick'
    | '/api/public/hooks/b3-mt5-commands-ack'
    | '/api/public/hooks/b3-mt5-commands-pending'
    | '/api/public/hooks/b3-mt5sim-tick'
    | '/api/public/hooks/b3-mt5sim-tick-ingest'
    | '/api/public/hooks/b3-simulation-tick'
    | '/api/public/hooks/confidence-recompute'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/health'
    | '/api/public/hooks/pipeline-tick'
    | '/api/public/hooks/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agent-rankings'
    | '/agents'
    | '/alerts'
    | '/approval-desk'
    | '/assets'
    | '/audit'
    | '/auto-dashboard'
    | '/b3'
    | '/b3-auditoria'
    | '/b3-mt5sim'
    | '/b3-sim-history'
    | '/b3-wdo'
    | '/binance-audit'
    | '/binance-brain'
    | '/binance-fee-audit'
    | '/binance-wallet-health'
    | '/committee'
    | '/council'
    | '/dashboard'
    | '/governance'
    | '/incidents'
    | '/intelligence'
    | '/kill-switch'
    | '/knowledge'
    | '/library'
    | '/logs'
    | '/metrics'
    | '/operations'
    | '/orders'
    | '/pipeline-diagnostics'
    | '/post-trade'
    | '/radar'
    | '/ranking'
    | '/real-dashboard'
    | '/real-risk'
    | '/recommendations'
    | '/regimes'
    | '/reports'
    | '/risk'
    | '/seasons'
    | '/settings'
    | '/strategic-memory'
    | '/strategy-lab'
    | '/supervisor'
    | '/wallet'
    | '/war-room'
    | '/analysis/$assetId'
    | '/audit/$reportId'
    | '/backtest/$runId'
    | '/backtest/criteria'
    | '/backtest/data'
    | '/backtest/new'
    | '/library/$expertId'
    | '/reports/$reportId'
    | '/backtest'
    | '/api/public/hooks/auto-tick'
    | '/api/public/hooks/b3-mt5-commands-ack'
    | '/api/public/hooks/b3-mt5-commands-pending'
    | '/api/public/hooks/b3-mt5sim-tick'
    | '/api/public/hooks/b3-mt5sim-tick-ingest'
    | '/api/public/hooks/b3-simulation-tick'
    | '/api/public/hooks/confidence-recompute'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/health'
    | '/api/public/hooks/pipeline-tick'
    | '/api/public/hooks/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agent-rankings'
    | '/_authenticated/agents'
    | '/_authenticated/alerts'
    | '/_authenticated/approval-desk'
    | '/_authenticated/assets'
    | '/_authenticated/audit'
    | '/_authenticated/auto-dashboard'
    | '/_authenticated/b3'
    | '/_authenticated/b3-auditoria'
    | '/_authenticated/b3-mt5sim'
    | '/_authenticated/b3-sim-history'
    | '/_authenticated/b3-wdo'
    | '/_authenticated/binance-audit'
    | '/_authenticated/binance-brain'
    | '/_authenticated/binance-fee-audit'
    | '/_authenticated/binance-wallet-health'
    | '/_authenticated/committee'
    | '/_authenticated/council'
    | '/_authenticated/dashboard'
    | '/_authenticated/governance'
    | '/_authenticated/incidents'
    | '/_authenticated/intelligence'
    | '/_authenticated/kill-switch'
    | '/_authenticated/knowledge'
    | '/_authenticated/library'
    | '/_authenticated/logs'
    | '/_authenticated/metrics'
    | '/_authenticated/operations'
    | '/_authenticated/orders'
    | '/_authenticated/pipeline-diagnostics'
    | '/_authenticated/post-trade'
    | '/_authenticated/radar'
    | '/_authenticated/ranking'
    | '/_authenticated/real-dashboard'
    | '/_authenticated/real-risk'
    | '/_authenticated/recommendations'
    | '/_authenticated/regimes'
    | '/_authenticated/reports'
    | '/_authenticated/risk'
    | '/_authenticated/seasons'
    | '/_authenticated/settings'
    | '/_authenticated/strategic-memory'
    | '/_authenticated/strategy-lab'
    | '/_authenticated/supervisor'
    | '/_authenticated/wallet'
    | '/_authenticated/war-room'
    | '/_authenticated/analysis/$assetId'
    | '/_authenticated/audit/$reportId'
    | '/_authenticated/backtest/$runId'
    | '/_authenticated/backtest/criteria'
    | '/_authenticated/backtest/data'
    | '/_authenticated/backtest/new'
    | '/_authenticated/library/$expertId'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/backtest/'
    | '/api/public/hooks/auto-tick'
    | '/api/public/hooks/b3-mt5-commands-ack'
    | '/api/public/hooks/b3-mt5-commands-pending'
    | '/api/public/hooks/b3-mt5sim-tick'
    | '/api/public/hooks/b3-mt5sim-tick-ingest'
    | '/api/public/hooks/b3-simulation-tick'
    | '/api/public/hooks/confidence-recompute'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/health'
    | '/api/public/hooks/pipeline-tick'
    | '/api/public/hooks/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAutoTickRoute: typeof ApiPublicHooksAutoTickRoute
  ApiPublicHooksB3Mt5CommandsAckRoute: typeof ApiPublicHooksB3Mt5CommandsAckRoute
  ApiPublicHooksB3Mt5CommandsPendingRoute: typeof ApiPublicHooksB3Mt5CommandsPendingRoute
  ApiPublicHooksB3Mt5simTickRoute: typeof ApiPublicHooksB3Mt5simTickRoute
  ApiPublicHooksB3Mt5simTickIngestRoute: typeof ApiPublicHooksB3Mt5simTickIngestRoute
  ApiPublicHooksB3SimulationTickRoute: typeof ApiPublicHooksB3SimulationTickRoute
  ApiPublicHooksConfidenceRecomputeRoute: typeof ApiPublicHooksConfidenceRecomputeRoute
  ApiPublicHooksDailyReportRoute: typeof ApiPublicHooksDailyReportRoute
  ApiPublicHooksHealthRoute: typeof ApiPublicHooksHealthRoute
  ApiPublicHooksPipelineTickRoute: typeof ApiPublicHooksPipelineTickRoute
  ApiPublicHooksWeeklyReportRoute: typeof ApiPublicHooksWeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/war-room': {
      id: '/_authenticated/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof AuthenticatedWarRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-lab': {
      id: '/_authenticated/strategy-lab'
      path: '/strategy-lab'
      fullPath: '/strategy-lab'
      preLoaderRoute: typeof AuthenticatedStrategyLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategic-memory': {
      id: '/_authenticated/strategic-memory'
      path: '/strategic-memory'
      fullPath: '/strategic-memory'
      preLoaderRoute: typeof AuthenticatedStrategicMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons': {
      id: '/_authenticated/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof AuthenticatedSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regimes': {
      id: '/_authenticated/regimes'
      path: '/regimes'
      fullPath: '/regimes'
      preLoaderRoute: typeof AuthenticatedRegimesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/real-risk': {
      id: '/_authenticated/real-risk'
      path: '/real-risk'
      fullPath: '/real-risk'
      preLoaderRoute: typeof AuthenticatedRealRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/real-dashboard': {
      id: '/_authenticated/real-dashboard'
      path: '/real-dashboard'
      fullPath: '/real-dashboard'
      preLoaderRoute: typeof AuthenticatedRealDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-trade': {
      id: '/_authenticated/post-trade'
      path: '/post-trade'
      fullPath: '/post-trade'
      preLoaderRoute: typeof AuthenticatedPostTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline-diagnostics': {
      id: '/_authenticated/pipeline-diagnostics'
      path: '/pipeline-diagnostics'
      fullPath: '/pipeline-diagnostics'
      preLoaderRoute: typeof AuthenticatedPipelineDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metrics': {
      id: '/_authenticated/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AuthenticatedMetricsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kill-switch': {
      id: '/_authenticated/kill-switch'
      path: '/kill-switch'
      fullPath: '/kill-switch'
      preLoaderRoute: typeof AuthenticatedKillSwitchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council': {
      id: '/_authenticated/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof AuthenticatedCouncilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee': {
      id: '/_authenticated/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof AuthenticatedCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/binance-wallet-health': {
      id: '/_authenticated/binance-wallet-health'
      path: '/binance-wallet-health'
      fullPath: '/binance-wallet-health'
      preLoaderRoute: typeof AuthenticatedBinanceWalletHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/binance-fee-audit': {
      id: '/_authenticated/binance-fee-audit'
      path: '/binance-fee-audit'
      fullPath: '/binance-fee-audit'
      preLoaderRoute: typeof AuthenticatedBinanceFeeAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/binance-brain': {
      id: '/_authenticated/binance-brain'
      path: '/binance-brain'
      fullPath: '/binance-brain'
      preLoaderRoute: typeof AuthenticatedBinanceBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/binance-audit': {
      id: '/_authenticated/binance-audit'
      path: '/binance-audit'
      fullPath: '/binance-audit'
      preLoaderRoute: typeof AuthenticatedBinanceAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/b3-wdo': {
      id: '/_authenticated/b3-wdo'
      path: '/b3-wdo'
      fullPath: '/b3-wdo'
      preLoaderRoute: typeof AuthenticatedB3WdoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/b3-sim-history': {
      id: '/_authenticated/b3-sim-history'
      path: '/b3-sim-history'
      fullPath: '/b3-sim-history'
      preLoaderRoute: typeof AuthenticatedB3SimHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/b3-mt5sim': {
      id: '/_authenticated/b3-mt5sim'
      path: '/b3-mt5sim'
      fullPath: '/b3-mt5sim'
      preLoaderRoute: typeof AuthenticatedB3Mt5simRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/b3-auditoria': {
      id: '/_authenticated/b3-auditoria'
      path: '/b3-auditoria'
      fullPath: '/b3-auditoria'
      preLoaderRoute: typeof AuthenticatedB3AuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/b3': {
      id: '/_authenticated/b3'
      path: '/b3'
      fullPath: '/b3'
      preLoaderRoute: typeof AuthenticatedB3RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auto-dashboard': {
      id: '/_authenticated/auto-dashboard'
      path: '/auto-dashboard'
      fullPath: '/auto-dashboard'
      preLoaderRoute: typeof AuthenticatedAutoDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approval-desk': {
      id: '/_authenticated/approval-desk'
      path: '/approval-desk'
      fullPath: '/approval-desk'
      preLoaderRoute: typeof AuthenticatedApprovalDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-rankings': {
      id: '/_authenticated/agent-rankings'
      path: '/agent-rankings'
      fullPath: '/agent-rankings'
      preLoaderRoute: typeof AuthenticatedAgentRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest/': {
      id: '/_authenticated/backtest/'
      path: '/backtest'
      fullPath: '/backtest/'
      preLoaderRoute: typeof AuthenticatedBacktestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/library/$expertId': {
      id: '/_authenticated/library/$expertId'
      path: '/$expertId'
      fullPath: '/library/$expertId'
      preLoaderRoute: typeof AuthenticatedLibraryExpertIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/backtest/new': {
      id: '/_authenticated/backtest/new'
      path: '/backtest/new'
      fullPath: '/backtest/new'
      preLoaderRoute: typeof AuthenticatedBacktestNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest/data': {
      id: '/_authenticated/backtest/data'
      path: '/backtest/data'
      fullPath: '/backtest/data'
      preLoaderRoute: typeof AuthenticatedBacktestDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest/criteria': {
      id: '/_authenticated/backtest/criteria'
      path: '/backtest/criteria'
      fullPath: '/backtest/criteria'
      preLoaderRoute: typeof AuthenticatedBacktestCriteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest/$runId': {
      id: '/_authenticated/backtest/$runId'
      path: '/backtest/$runId'
      fullPath: '/backtest/$runId'
      preLoaderRoute: typeof AuthenticatedBacktestRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/$reportId': {
      id: '/_authenticated/audit/$reportId'
      path: '/$reportId'
      fullPath: '/audit/$reportId'
      preLoaderRoute: typeof AuthenticatedAuditReportIdRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
    '/_authenticated/analysis/$assetId': {
      id: '/_authenticated/analysis/$assetId'
      path: '/analysis/$assetId'
      fullPath: '/analysis/$assetId'
      preLoaderRoute: typeof AuthenticatedAnalysisAssetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/weekly-report': {
      id: '/api/public/hooks/weekly-report'
      path: '/api/public/hooks/weekly-report'
      fullPath: '/api/public/hooks/weekly-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pipeline-tick': {
      id: '/api/public/hooks/pipeline-tick'
      path: '/api/public/hooks/pipeline-tick'
      fullPath: '/api/public/hooks/pipeline-tick'
      preLoaderRoute: typeof ApiPublicHooksPipelineTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health': {
      id: '/api/public/hooks/health'
      path: '/api/public/hooks/health'
      fullPath: '/api/public/hooks/health'
      preLoaderRoute: typeof ApiPublicHooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-report': {
      id: '/api/public/hooks/daily-report'
      path: '/api/public/hooks/daily-report'
      fullPath: '/api/public/hooks/daily-report'
      preLoaderRoute: typeof ApiPublicHooksDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/confidence-recompute': {
      id: '/api/public/hooks/confidence-recompute'
      path: '/api/public/hooks/confidence-recompute'
      fullPath: '/api/public/hooks/confidence-recompute'
      preLoaderRoute: typeof ApiPublicHooksConfidenceRecomputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/b3-simulation-tick': {
      id: '/api/public/hooks/b3-simulation-tick'
      path: '/api/public/hooks/b3-simulation-tick'
      fullPath: '/api/public/hooks/b3-simulation-tick'
      preLoaderRoute: typeof ApiPublicHooksB3SimulationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/b3-mt5sim-tick-ingest': {
      id: '/api/public/hooks/b3-mt5sim-tick-ingest'
      path: '/api/public/hooks/b3-mt5sim-tick-ingest'
      fullPath: '/api/public/hooks/b3-mt5sim-tick-ingest'
      preLoaderRoute: typeof ApiPublicHooksB3Mt5simTickIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/b3-mt5sim-tick': {
      id: '/api/public/hooks/b3-mt5sim-tick'
      path: '/api/public/hooks/b3-mt5sim-tick'
      fullPath: '/api/public/hooks/b3-mt5sim-tick'
      preLoaderRoute: typeof ApiPublicHooksB3Mt5simTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/b3-mt5-commands-pending': {
      id: '/api/public/hooks/b3-mt5-commands-pending'
      path: '/api/public/hooks/b3-mt5-commands-pending'
      fullPath: '/api/public/hooks/b3-mt5-commands-pending'
      preLoaderRoute: typeof ApiPublicHooksB3Mt5CommandsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/b3-mt5-commands-ack': {
      id: '/api/public/hooks/b3-mt5-commands-ack'
      path: '/api/public/hooks/b3-mt5-commands-ack'
      fullPath: '/api/public/hooks/b3-mt5-commands-ack'
      preLoaderRoute: typeof ApiPublicHooksB3Mt5CommandsAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-tick': {
      id: '/api/public/hooks/auto-tick'
      path: '/api/public/hooks/auto-tick'
      fullPath: '/api/public/hooks/auto-tick'
      preLoaderRoute: typeof ApiPublicHooksAutoTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAuditRouteChildren {
  AuthenticatedAuditReportIdRoute: typeof AuthenticatedAuditReportIdRoute
}

const AuthenticatedAuditRouteChildren: AuthenticatedAuditRouteChildren = {
  AuthenticatedAuditReportIdRoute: AuthenticatedAuditReportIdRoute,
}

const AuthenticatedAuditRouteWithChildren =
  AuthenticatedAuditRoute._addFileChildren(AuthenticatedAuditRouteChildren)

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryExpertIdRoute: typeof AuthenticatedLibraryExpertIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryExpertIdRoute: AuthenticatedLibraryExpertIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRankingsRoute: typeof AuthenticatedAgentRankingsRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedApprovalDeskRoute: typeof AuthenticatedApprovalDeskRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRouteWithChildren
  AuthenticatedAutoDashboardRoute: typeof AuthenticatedAutoDashboardRoute
  AuthenticatedB3Route: typeof AuthenticatedB3Route
  AuthenticatedB3AuditoriaRoute: typeof AuthenticatedB3AuditoriaRoute
  AuthenticatedB3Mt5simRoute: typeof AuthenticatedB3Mt5simRoute
  AuthenticatedB3SimHistoryRoute: typeof AuthenticatedB3SimHistoryRoute
  AuthenticatedB3WdoRoute: typeof AuthenticatedB3WdoRoute
  AuthenticatedBinanceAuditRoute: typeof AuthenticatedBinanceAuditRoute
  AuthenticatedBinanceBrainRoute: typeof AuthenticatedBinanceBrainRoute
  AuthenticatedBinanceFeeAuditRoute: typeof AuthenticatedBinanceFeeAuditRoute
  AuthenticatedBinanceWalletHealthRoute: typeof AuthenticatedBinanceWalletHealthRoute
  AuthenticatedCommitteeRoute: typeof AuthenticatedCommitteeRoute
  AuthenticatedCouncilRoute: typeof AuthenticatedCouncilRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedKillSwitchRoute: typeof AuthenticatedKillSwitchRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMetricsRoute: typeof AuthenticatedMetricsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPipelineDiagnosticsRoute: typeof AuthenticatedPipelineDiagnosticsRoute
  AuthenticatedPostTradeRoute: typeof AuthenticatedPostTradeRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRealDashboardRoute: typeof AuthenticatedRealDashboardRoute
  AuthenticatedRealRiskRoute: typeof AuthenticatedRealRiskRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRegimesRoute: typeof AuthenticatedRegimesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSeasonsRoute: typeof AuthenticatedSeasonsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategicMemoryRoute: typeof AuthenticatedStrategicMemoryRoute
  AuthenticatedStrategyLabRoute: typeof AuthenticatedStrategyLabRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWarRoomRoute: typeof AuthenticatedWarRoomRoute
  AuthenticatedAnalysisAssetIdRoute: typeof AuthenticatedAnalysisAssetIdRoute
  AuthenticatedBacktestRunIdRoute: typeof AuthenticatedBacktestRunIdRoute
  AuthenticatedBacktestCriteriaRoute: typeof AuthenticatedBacktestCriteriaRoute
  AuthenticatedBacktestDataRoute: typeof AuthenticatedBacktestDataRoute
  AuthenticatedBacktestNewRoute: typeof AuthenticatedBacktestNewRoute
  AuthenticatedBacktestIndexRoute: typeof AuthenticatedBacktestIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRankingsRoute: AuthenticatedAgentRankingsRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedApprovalDeskRoute: AuthenticatedApprovalDeskRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRouteWithChildren,
  AuthenticatedAutoDashboardRoute: AuthenticatedAutoDashboardRoute,
  AuthenticatedB3Route: AuthenticatedB3Route,
  AuthenticatedB3AuditoriaRoute: AuthenticatedB3AuditoriaRoute,
  AuthenticatedB3Mt5simRoute: AuthenticatedB3Mt5simRoute,
  AuthenticatedB3SimHistoryRoute: AuthenticatedB3SimHistoryRoute,
  AuthenticatedB3WdoRoute: AuthenticatedB3WdoRoute,
  AuthenticatedBinanceAuditRoute: AuthenticatedBinanceAuditRoute,
  AuthenticatedBinanceBrainRoute: AuthenticatedBinanceBrainRoute,
  AuthenticatedBinanceFeeAuditRoute: AuthenticatedBinanceFeeAuditRoute,
  AuthenticatedBinanceWalletHealthRoute: AuthenticatedBinanceWalletHealthRoute,
  AuthenticatedCommitteeRoute: AuthenticatedCommitteeRoute,
  AuthenticatedCouncilRoute: AuthenticatedCouncilRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedKillSwitchRoute: AuthenticatedKillSwitchRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMetricsRoute: AuthenticatedMetricsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPipelineDiagnosticsRoute: AuthenticatedPipelineDiagnosticsRoute,
  AuthenticatedPostTradeRoute: AuthenticatedPostTradeRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRealDashboardRoute: AuthenticatedRealDashboardRoute,
  AuthenticatedRealRiskRoute: AuthenticatedRealRiskRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRegimesRoute: AuthenticatedRegimesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSeasonsRoute: AuthenticatedSeasonsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategicMemoryRoute: AuthenticatedStrategicMemoryRoute,
  AuthenticatedStrategyLabRoute: AuthenticatedStrategyLabRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWarRoomRoute: AuthenticatedWarRoomRoute,
  AuthenticatedAnalysisAssetIdRoute: AuthenticatedAnalysisAssetIdRoute,
  AuthenticatedBacktestRunIdRoute: AuthenticatedBacktestRunIdRoute,
  AuthenticatedBacktestCriteriaRoute: AuthenticatedBacktestCriteriaRoute,
  AuthenticatedBacktestDataRoute: AuthenticatedBacktestDataRoute,
  AuthenticatedBacktestNewRoute: AuthenticatedBacktestNewRoute,
  AuthenticatedBacktestIndexRoute: AuthenticatedBacktestIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAutoTickRoute: ApiPublicHooksAutoTickRoute,
  ApiPublicHooksB3Mt5CommandsAckRoute: ApiPublicHooksB3Mt5CommandsAckRoute,
  ApiPublicHooksB3Mt5CommandsPendingRoute:
    ApiPublicHooksB3Mt5CommandsPendingRoute,
  ApiPublicHooksB3Mt5simTickRoute: ApiPublicHooksB3Mt5simTickRoute,
  ApiPublicHooksB3Mt5simTickIngestRoute: ApiPublicHooksB3Mt5simTickIngestRoute,
  ApiPublicHooksB3SimulationTickRoute: ApiPublicHooksB3SimulationTickRoute,
  ApiPublicHooksConfidenceRecomputeRoute:
    ApiPublicHooksConfidenceRecomputeRoute,
  ApiPublicHooksDailyReportRoute: ApiPublicHooksDailyReportRoute,
  ApiPublicHooksHealthRoute: ApiPublicHooksHealthRoute,
  ApiPublicHooksPipelineTickRoute: ApiPublicHooksPipelineTickRoute,
  ApiPublicHooksWeeklyReportRoute: ApiPublicHooksWeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
